Data Cleaning and Analysis

### Step 1: Import Libraries

In [1]:
import pandas as pd

### Step 2: Load the Dataset

In [55]:
ud = pd.read_csv("../data/raw/UsedDevices-Haraj-k.csv")

### Step 3: Data Inspection

In [6]:
ud.shape

(438, 11)

In [27]:
ud.columns

Index(['Unnamed: 0', 'id', 'title', 'city', 'postDate', 'updateDate', 'tags',
       'commentCount', 'upRank', 'downRank', 'start_price'],
      dtype='str')

In [113]:
ud.dtypes

unnamed:_0         int64
id                 int64
title                str
city                 str
post_date            str
update_date          str
tags              object
comment_count      int64
up_rank            int64
down_rank          int64
start_price      float64
dtype: object

#### 3.1 cheack text columns

In [10]:
text_columns = ud.select_dtypes(include="str").columns

In [11]:
print(text_columns)

Index(['title', 'city', 'postDate', 'updateDate', 'tags'], dtype='str')

In [14]:
ud[text_columns].dtypes

title         str
city          str
postDate      str
updateDate    str
tags          str
dtype: object

In [15]:
ud[text_columns].isnull().sum()

title         0
city          0
postDate      0
updateDate    0
tags          0
dtype: int64

In [18]:
for col in text_columns : 
   print(col, ud[col].duplicated().sum())

title 7
city 422
postDate 9
updateDate 9
tags 316

In [21]:
for col in text_columns :
    print(f"\n{col} : {ud[col].nunique()} unique value ")

title : 431 unique value

city : 16 unique value

postDate : 429 unique value

updateDate : 429 unique value

tags : 122 unique value

In [32]:
for col in text_columns :
    print(f"/n{col} :")
    print(ud[col].dropna().head(10).tolist())

/ntitle :
['ارقام سوا لللبيع', 'رقم للبيع مميزز 0598064', 'للبيع ارقام سوا مميزة', 'رقمم مميز جدا ثنائي خماسي للبيع', 'رقم stc مميز', 'شرايح موبايلي مجانا', 'ارقام  مميزة Stc', 'رقم مميز 888', 'رقمين طقم مميزه', 'رقم مميز VIP']
/ncity :
['الرياض', 'الرياض', 'جده', 'جده', 'الشرقيه', 'المدينة', 'الرياض', 'الطايف', 'الرياض', 'الرياض']
/npostDate :
['2021-01-30 18:23:54', '2021-01-30 18:22:52', '2021-01-30 18:12:34', '2021-01-30 18:11:53', '2021-01-30 18:01:32', '2021-01-30 17:56:12', '2021-01-30 17:55:24', '2021-01-30 17:54:10', '2021-01-30 17:48:48', '2021-01-30 17:45:44']
/nupdateDate :
['2021-01-30 18:23:54', '2021-01-30 18:22:52', '2021-01-30 18:12:34', '2021-01-30 18:11:53', '2021-01-30 18:01:32', '2021-01-30 17:56:12', '2021-01-30 17:55:24', '2021-01-30 17:54:10', '2021-01-30 17:48:48', '2021-01-30 17:45:44']
/ntags :
["['أرقام مميزة', 'ارقام مميزة من الاتصالات السعودية STC', 'حراج الأجهزة']", "['أرقام مميزة', 'ارقام مميزة من الاتصالات السعودية STC', 'حراج الأجهزة']", "['أرقام مميزة', 'ارقام مميزة من الاتصالات السعودية STC', 'حراج الأجهزة', 'كل الحراج']", "['empty', 'أرقام مميزة', 'ارقام مميزة من الاتصالات السعودية STC', 'حراج الأجهزة']", "['أرقام مميزة', 'ارقام مميزة من الاتصالات السعودية STC', 'حراج الأجهزة']", "['أرقام مميزة', 'ارقام مميزة من موبايلي Mobily', 'حراج الأجهزة']", "['أرقام مميزة', 'ارقام مميزة من الاتصالات السعودية STC', 'حراج الأجهزة']", "['أرقام مميزة', 'ارقام مميزة من زين Zain', 'حراج الأجهزة']", "['أرقام مميزة', 'ارقام مميزة من الاتصالات السعودية STC', 'حراج الأجهزة', 'كل الحراج']", "['أرقام مميزة', 'ارقام مميزة من موبايلي Mobily', 'حراج الأجهزة']"]

In [34]:
# Check for leading or trailing spaces
print("\nLeading/Trailing Spaces:")
for col in text_columns:
    spaces = ud[col].dropna().astype(str).str.strip().ne(ud[col].dropna().astype(str))
    print(f"{col}: {spaces.sum()} values with extra spaces")

Leading/Trailing Spaces:
title: 2 values with extra spaces
city: 0 values with extra spaces
postDate: 0 values with extra spaces
updateDate: 0 values with extra spaces
tags: 0 values with extra spaces

In [36]:
# Check empty strings
print("\nEmpty Strings:")
for col in text_columns:
    empty = ud[col].fillna("").astype(str).str.strip().eq("")
    print(f"{col}: {empty.sum()} empty values")

Empty Strings:
title: 0 empty values
city: 0 empty values
postDate: 0 empty values
updateDate: 0 empty values
tags: 0 empty values

In [37]:
# Check text length
print("\nText Length:")
for col in text_columns:
    print(f"\n{col}:")
    print(ud[col].dropna().astype(str).str.len().describe())

Text Length:

title:
count    438.000000
mean      21.865297
std       10.492348
min        4.000000
25%       13.000000
50%       20.000000
75%       28.000000
max       50.000000
Name: title, dtype: float64

city:
count    438.000000
mean       5.262557
std        1.600061
min        3.000000
25%        3.250000
50%        6.000000
75%        6.000000
max       10.000000
Name: city, dtype: float64

postDate:
count    438.0
mean      19.0
std        0.0
min       19.0
25%       19.0
50%       19.0
75%       19.0
max       19.0
Name: postDate, dtype: float64

updateDate:
count    438.0
mean      19.0
std        0.0
min       19.0
25%       19.0
50%       19.0
75%       19.0
max       19.0
Name: updateDate, dtype: float64

tags:
count    438.000000
mean      42.609589
std       13.629306
min       28.000000
25%       32.000000
50%       40.000000
75%       48.000000
max       89.000000
Name: tags, dtype: float64

#### 3.2 cheack numeric columns

In [58]:
numeric_columns = ud.select_dtypes(include="number").columns

In [103]:
ud[numeric_columns].describe()

,Unnamed: 0,id,commentCount,upRank,downRank,start_price
count,438.000000,4.380000e+02,438.000000,438.000000,438.000000,4.380000e+02
mean,199.413242,6.989797e+07,0.821918,3.315068,0.002283,1.142984e+06
std,125.133377,6.342358e+04,1.876087,17.603081,0.047782,2.391504e+07
min,0.000000,6.954758e+07,0.000000,0.000000,0.000000,0.000000e+00
25%,89.250000,6.989513e+07,0.000000,0.000000,0.000000,0.000000e+00
50%,198.500000,6.992709e+07,0.000000,0.000000,0.000000,0.000000e+00
75%,307.750000,6.993439e+07,1.000000,0.000000,0.000000,5.000000e+01
max,417.000000,6.993840e+07,17.000000,270.000000,1.000000,5.005051e+08

In [100]:
ud[numeric_columns].isnull().sum()

Unnamed: 0      0
id              0
commentCount    0
upRank          0
downRank        0
start_price     0
dtype: int64

In [101]:
for col in numeric_columns : 
    print(col , (ud[col]<0).sum())

Unnamed: 0 0
id 0
commentCount 0
upRank 0
downRank 0
start_price 0

In [102]:
for col in numeric_columns:
    print(col, ud[col].nunique())

Unnamed: 0 418
id 438
commentCount 12
upRank 33
downRank 2
start_price 51

In [66]:
for col in numeric_columns:
    Q1 = ud[col].quantile(0.25)
    Q3 = ud[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((ud[col] < lower) | (ud[col] > upper)).sum()

    print(f"{col}: {outliers}")

Unnamed: 0: 0
id: 68
commentCount: 49
upRank: 84
downRank: 1
start_price: 103

#### 3.3 cheack date colmuns

In [67]:
date_columns = ["postDate" , "updateDate"]

In [68]:
for col in date_columns:
    print(f"{col}: {ud[col].dtype}")

postDate: str
updateDate: str

In [69]:
for col in date_columns:
    print(f"\n{col}:")
    print(ud[col].dropna().head(10))

postDate:
0    2021-01-30 18:23:54
1    2021-01-30 18:22:52
2    2021-01-30 18:12:34
3    2021-01-30 18:11:53
4    2021-01-30 18:01:32
5    2021-01-30 17:56:12
6    2021-01-30 17:55:24
7    2021-01-30 17:54:10
8    2021-01-30 17:48:48
9    2021-01-30 17:45:44
Name: postDate, dtype: str

updateDate:
0    2021-01-30 18:23:54
1    2021-01-30 18:22:52
2    2021-01-30 18:12:34
3    2021-01-30 18:11:53
4    2021-01-30 18:01:32
5    2021-01-30 17:56:12
6    2021-01-30 17:55:24
7    2021-01-30 17:54:10
8    2021-01-30 17:48:48
9    2021-01-30 17:45:44
Name: updateDate, dtype: str

In [70]:
for col in date_columns:
    print(f"{col}: {ud[col].isna().sum()}")

postDate: 0
updateDate: 0

In [71]:
for col in date_columns:
    print(f"\n{col}:")
    print(ud[col].dropna().unique()[:20])

postDate:
<ArrowStringArray>
['2021-01-30 18:23:54', '2021-01-30 18:22:52', '2021-01-30 18:12:34',
 '2021-01-30 18:11:53', '2021-01-30 18:01:32', '2021-01-30 17:56:12',
 '2021-01-30 17:55:24', '2021-01-30 17:54:10', '2021-01-30 17:48:48',
 '2021-01-30 17:45:44', '2021-01-30 17:42:47', '2021-01-30 17:26:46',
 '2021-01-30 17:19:00', '2021-01-30 17:17:08', '2021-01-30 17:14:53',
 '2021-01-30 17:13:33', '2021-01-30 17:11:38', '2021-01-30 17:10:56',
 '2021-01-30 17:07:47', '2021-01-30 17:07:27']
Length: 20, dtype: str

updateDate:
<ArrowStringArray>
['2021-01-30 18:23:54', '2021-01-30 18:22:52', '2021-01-30 18:12:34',
 '2021-01-30 18:11:53', '2021-01-30 18:01:32', '2021-01-30 17:56:12',
 '2021-01-30 17:55:24', '2021-01-30 17:54:10', '2021-01-30 17:48:48',
 '2021-01-30 17:45:44', '2021-01-30 17:42:47', '2021-01-30 17:26:46',
 '2021-01-30 17:19:00', '2021-01-30 17:17:08', '2021-01-30 17:14:53',
 '2021-01-30 17:13:33', '2021-01-30 17:11:38', '2021-01-30 17:10:56',
 '2021-01-30 17:07:47', '2021-01-30 17:07:27']
Length: 20, dtype: str

In [72]:
for col in date_columns:
    temp_dates = pd.to_datetime(ud[col], errors="coerce")
    
    invalid = ud[col].notna() & temp_dates.isna()
    
    print(f"\n{col}: {invalid.sum()} invalid dates")
    print(ud.loc[invalid, col].head(10))

postDate: 0 invalid dates
Series([], Name: postDate, dtype: str)

updateDate: 0 invalid dates
Series([], Name: updateDate, dtype: str)

###  step 4 : Memory Usage Before Cleaning and Optimization

In [109]:
memory_before = ud.memory_usage(deep=True).sum()

print(f"Memory usage before optimization: {memory_before / 1024**2:.2f} MB")

Memory usage before optimization: 0.11 MB

### step 5 : Data Cleaning

In [78]:
import ast

In [79]:
ud["tags"]= ud["tags"].apply(lambda x :ast.literal_eval(x) if pd.notna else x)

In [ ]:

def clean_tags(tags):
    if not isinstance(tags, list):
        return tags

    tags = [
        tag.strip().lower()
        for tag in tags
        if tag.strip().lower() != "empty"
    ]
    

    tags = list(dict.fromkeys(tags))

    return tags if tags else pd.NA

In [99]:
ud["tags"]=ud["tags"].apply(clean_tags)

In [88]:
ud[["city" , "title"]] = ud[["city" , "title"]].apply(lambda col: col.str.strip().str.lower() )

In [104]:
ud[ud["start_price"] > 1000][["start_price"]]

     start_price
14     500505080
15         13000
54          1550
65          1500
73          3500
74          2500
99          4000
100         1700
103         2500
110         3700
121         3600
124         3000
129         2500
131         1800
164         1400
175         1900
200         1500
215         5000
218         3000
227         1500
231         1200
233         2000
234         1500
277         1300
303         1300
359         7999
363         1350
370         1850
377         2850
381         1700
395         2000
422         2500
435         1800

In [105]:
ud.loc[14]

Unnamed: 0                                                     14
id                                                       69931548
title                                   رقم مميز للبيع 0500505080
city                                                       الرياض
postDate                                      2021-01-30 17:14:53
updateDate                                    2021-01-30 17:14:53
tags            [أرقام مميزة, ارقام مميزة من الاتصالات السعودي...
commentCount                                                    0
upRank                                                          0
downRank                                                        0
start_price                                             500505080
Name: 14, dtype: object

In [106]:
ud.loc[14, "start_price"] = pd.NA

In [108]:
df = ud.drop(columns="Unnamed: 0")

In [110]:
ud.columns = (
    ud.columns
    .str.strip()
    .str.replace(r"(?<!^)(?=[A-Z])", "_", regex=True)
    .str.replace(" ", "_")
    .str.lower()
)

In [111]:
ud.columns

Index(['unnamed:_0', 'id', 'title', 'city', 'post_date', 'update_date', 'tags',
       'comment_count', 'up_rank', 'down_rank', 'start_price'],
      dtype='str')

### step 6: Optimize and convert data types

In [115]:
ud["city"] = ud["city"].astype("category")

In [116]:
ud["post_date"] = pd.to_datetime(ud["post_date"])

In [117]:
ud["update_date"] = pd.to_datetime(ud["update_date"])

###  step 7 : Memory Usage After Cleaning and Optimization

In [119]:
memory_after = ud.memory_usage(deep=True).sum()

print(f"Memory usage after optimization: {memory_after / 1024**2:.2f} MB")

Memory usage after optimization: 0.08 MB

### Step 8: Data Validation

In [122]:
print("Shape:")
print(ud.shape)

Shape:
(438, 11)

In [123]:
print("\nColumn Names:")
print(ud.columns.tolist())

Column Names:
['unnamed:_0', 'id', 'title', 'city', 'post_date', 'update_date', 'tags', 'comment_count', 'up_rank', 'down_rank', 'start_price']

In [124]:
print("\nData Types:")
print(ud.dtypes)

Data Types:
unnamed:_0                int64
id                        int64
title                       str
city                   category
post_date        datetime64[us]
update_date      datetime64[us]
tags                     object
comment_count             int64
up_rank                   int64
down_rank                 int64
start_price             float64
dtype: object

In [125]:
print("\nMissing Values:")
print(ud.isna().sum())

Missing Values:
unnamed:_0       0
id               0
title            0
city             0
post_date        0
update_date      0
tags             0
comment_count    0
up_rank          0
down_rank        0
start_price      1
dtype: int64

In [127]:
print("\nDuplicate Rows:")
df.drop(columns=["tags"]).duplicated().sum()

Duplicate Rows:

np.int64(0)

In [129]:
print("\nNegative Values:")
for col in numeric_columns:
    if col in ud.columns:
        print(f"{col}: {(ud[col] < 0).sum()}")

Negative Values:
id: 0
start_price: 0

In [130]:
saved = memory_before - memory_after

print(f"Memory saved: {saved / 1024**2:.2f} MB")

Memory saved: 0.02 MB

In [131]:
saving_percent = (saved / memory_before) * 100

print(f"Memory saving: {saving_percent:.2f}%")

Memory saving: 21.61%

In [132]:
ud.to_parquet(
    "../data/cleaned/usedDevices",
    index=False
)